package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            name = "Wait for 15 Seconds"
            id = "sleeper"
            scriptContent = "sleep 15"
        }
        script {
            id = "simpleRunner"
            scriptContent = """
                chmod +x calculate.sh
                ./calculate.sh
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            name = "Wait for 30 Seconds"
            clearConditions()
            scriptContent = "sleep 30"
            dockerImage = "ruby:100.100"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }

    features {
        add {
            pullRequests {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                provider = github {
                    authType = token {
                        token = "cks4ea90cfd9966b6e7eb6590d86fc4b046N8qPV1+pbe0ucErdoG8kTeGwu15TrhhZ7GxbOTd5YFZ2GrPBEiuGeovXbexMaMnX"
                    }
                    filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
                    ignoreDrafts = true
                }
            }
        }
    }
}
