package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            name = "Wait for 11 Seconds"
            id = "sleeper"
            scriptContent = "sleep 11"
        }
        script {
            id = "simpleRunner"
            scriptContent = """
                chmod +x calculate.sh
                ./calculate.sh
            """.trimIndent()
        }
    }
    steps {
        insert(2) {
            maven {
                id = "Maven2"
                goals = "clean test"
                pomLocation = ".teamcity/pom.xml"
                runnerArgs = "-Dmaven.test.failure.ignore=true"
            }
        }
        insert(3) {
            script {
                id = "simpleRunner_1"
                scriptContent = "./calculate.sh"
            }
        }
    }

    features {
        add {
            pullRequests {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                provider = github {
                    authType = token {
                        token = "cks4ea90cfd9966b6e7eb6590d86fc4b046N8qPV1+pbe0ucErdoG8kTeGwu15TrhhZ7GxbOTd5YFZ2GrPBEiuGeovXbexMaMnX"
                    }
                    filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
                    ignoreDrafts = true
                }
            }
        }
    }
}
